/*
 * LoginID Service API
 * # Introduction  <span class=\"subtext\"> Welcome to the LoginID API docs. This documentation will help understand the API calls being made behind our SDKs.  These APIs can be used to manage authentication, users, and user credentials. </span>  # Authentication  <span class=\"subtext\"> There is one main form of authentication for the API: <br/>&bull; API Service Token </span> 
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.loginid.sdk.java.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Credentialsfido2completeAttestationPayload
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-10T08:30:05.952Z[GMT]")
public class Credentialsfido2completeAttestationPayload {
  @SerializedName("credential_uuid")
  private String credentialUuid = null;

  @SerializedName("credential_id")
  private String credentialId = null;

  @SerializedName("challenge")
  private String challenge = null;

  @SerializedName("client_data")
  private String clientData = null;

  @SerializedName("attestation_data")
  private String attestationData = null;

  public Credentialsfido2completeAttestationPayload credentialUuid(String credentialUuid) {
    this.credentialUuid = credentialUuid;
    return this;
  }

   /**
   * Get credentialUuid
   * @return credentialUuid
  **/
  @Schema(description = "")
  public String getCredentialUuid() {
    return credentialUuid;
  }

  public void setCredentialUuid(String credentialUuid) {
    this.credentialUuid = credentialUuid;
  }

  public Credentialsfido2completeAttestationPayload credentialId(String credentialId) {
    this.credentialId = credentialId;
    return this;
  }

   /**
   * Get credentialId
   * @return credentialId
  **/
  @Schema(description = "")
  public String getCredentialId() {
    return credentialId;
  }

  public void setCredentialId(String credentialId) {
    this.credentialId = credentialId;
  }

  public Credentialsfido2completeAttestationPayload challenge(String challenge) {
    this.challenge = challenge;
    return this;
  }

   /**
   * Get challenge
   * @return challenge
  **/
  @Schema(description = "")
  public String getChallenge() {
    return challenge;
  }

  public void setChallenge(String challenge) {
    this.challenge = challenge;
  }

  public Credentialsfido2completeAttestationPayload clientData(String clientData) {
    this.clientData = clientData;
    return this;
  }

   /**
   * Get clientData
   * @return clientData
  **/
  @Schema(description = "")
  public String getClientData() {
    return clientData;
  }

  public void setClientData(String clientData) {
    this.clientData = clientData;
  }

  public Credentialsfido2completeAttestationPayload attestationData(String attestationData) {
    this.attestationData = attestationData;
    return this;
  }

   /**
   * Get attestationData
   * @return attestationData
  **/
  @Schema(description = "")
  public String getAttestationData() {
    return attestationData;
  }

  public void setAttestationData(String attestationData) {
    this.attestationData = attestationData;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Credentialsfido2completeAttestationPayload credentialsfido2completeAttestationPayload = (Credentialsfido2completeAttestationPayload) o;
    return Objects.equals(this.credentialUuid, credentialsfido2completeAttestationPayload.credentialUuid) &&
        Objects.equals(this.credentialId, credentialsfido2completeAttestationPayload.credentialId) &&
        Objects.equals(this.challenge, credentialsfido2completeAttestationPayload.challenge) &&
        Objects.equals(this.clientData, credentialsfido2completeAttestationPayload.clientData) &&
        Objects.equals(this.attestationData, credentialsfido2completeAttestationPayload.attestationData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(credentialUuid, credentialId, challenge, clientData, attestationData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Credentialsfido2completeAttestationPayload {\n");

    sb.append("    credentialUuid: ").append(toIndentedString(credentialUuid)).append("\n");
    sb.append("    credentialId: ").append(toIndentedString(credentialId)).append("\n");
    sb.append("    challenge: ").append(toIndentedString(challenge)).append("\n");
    sb.append("    clientData: ").append(toIndentedString(clientData)).append("\n");
    sb.append("    attestationData: ").append(toIndentedString(attestationData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
