/*
 * LoginID Service API
 * # Introduction  <span class=\"subtext\"> Welcome to the LoginID API docs. This documentation will help understand the API calls being made behind our SDKs.  These APIs can be used to manage authentication, users, and user credentials. </span>  # Authentication  <span class=\"subtext\"> There is one main form of authentication for the API: <br/>&bull; API Service Token </span> 
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.loginid.sdk.java.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * InlineResponse2003
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-10T08:30:05.952Z[GMT]")
public class InlineResponse2003 {
  @SerializedName("assertion_payload")
  private InlineResponse2003AssertionPayload assertionPayload = null;

  public InlineResponse2003 assertionPayload(InlineResponse2003AssertionPayload assertionPayload) {
    this.assertionPayload = assertionPayload;
    return this;
  }

   /**
   * Get assertionPayload
   * @return assertionPayload
  **/
  @Schema(description = "")
  public InlineResponse2003AssertionPayload getAssertionPayload() {
    return assertionPayload;
  }

  public void setAssertionPayload(InlineResponse2003AssertionPayload assertionPayload) {
    this.assertionPayload = assertionPayload;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2003 inlineResponse2003 = (InlineResponse2003) o;
    return Objects.equals(this.assertionPayload, inlineResponse2003.assertionPayload);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assertionPayload);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2003 {\n");

    sb.append("    assertionPayload: ").append(toIndentedString(assertionPayload)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
