/*
 * LoginID Service API
 * # Introduction  <span class=\"subtext\"> Welcome to the LoginID API docs. This documentation will help understand the API calls being made behind our SDKs.  These APIs can be used to manage authentication, users, and user credentials. </span>  # Authentication  <span class=\"subtext\"> There is one main form of authentication for the API: <br/>&bull; API Service Token </span> 
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.loginid.sdk.java.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * RegistercompletePayload
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-10T08:30:05.952Z[GMT]")
public class RegistercompletePayload {
  @SerializedName("challenge")
  private String challenge = null;

  @SerializedName("credential_id")
  private String credentialId = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("raw_id")
  private String rawId = null;

  @SerializedName("attestation_data")
  private String attestationData = null;

  @SerializedName("client_data")
  private String clientData = null;

  public RegistercompletePayload challenge(String challenge) {
    this.challenge = challenge;
    return this;
  }

   /**
   * Get challenge
   * @return challenge
  **/
  @Schema(example = "pO9V4DruYKrXClSwUn9pRIapBfFcl_l0khQd7YwqQRE", description = "")
  public String getChallenge() {
    return challenge;
  }

  public void setChallenge(String challenge) {
    this.challenge = challenge;
  }

  public RegistercompletePayload credentialId(String credentialId) {
    this.credentialId = credentialId;
    return this;
  }

   /**
   * Get credentialId
   * @return credentialId
  **/
  @Schema(example = "b7bd9990-2c43-4dce-9286-93cccf81bc62", description = "")
  public String getCredentialId() {
    return credentialId;
  }

  public void setCredentialId(String credentialId) {
    this.credentialId = credentialId;
  }

  public RegistercompletePayload id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(example = "5dEDbWqk0BAc1lKwFI057rkTHPd7zHBvlDb5pd_HlTw", description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public RegistercompletePayload rawId(String rawId) {
    this.rawId = rawId;
    return this;
  }

   /**
   * Get rawId
   * @return rawId
  **/
  @Schema(example = "5dEDbWqk0BAc1lKwFI057rkTHPd7zHBvlDb5pd_HlTw", description = "")
  public String getRawId() {
    return rawId;
  }

  public void setRawId(String rawId) {
    this.rawId = rawId;
  }

  public RegistercompletePayload attestationData(String attestationData) {
    this.attestationData = attestationData;
    return this;
  }

   /**
   * Get attestationData
   * @return attestationData
  **/
  @Schema(example = "b7bd9990-2c43-4dce-9286-93cccf81bc62", description = "")
  public String getAttestationData() {
    return attestationData;
  }

  public void setAttestationData(String attestationData) {
    this.attestationData = attestationData;
  }

  public RegistercompletePayload clientData(String clientData) {
    this.clientData = clientData;
    return this;
  }

   /**
   * Get clientData
   * @return clientData
  **/
  @Schema(example = "eyJ0eXBlIjoid2ViYXV0aG4uY3JlYXRlIiwiY2hhbGxlbmdlIjoicE85VjREcnVZS3JYQ2x", description = "")
  public String getClientData() {
    return clientData;
  }

  public void setClientData(String clientData) {
    this.clientData = clientData;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegistercompletePayload registercompletePayload = (RegistercompletePayload) o;
    return Objects.equals(this.challenge, registercompletePayload.challenge) &&
        Objects.equals(this.credentialId, registercompletePayload.credentialId) &&
        Objects.equals(this.id, registercompletePayload.id) &&
        Objects.equals(this.rawId, registercompletePayload.rawId) &&
        Objects.equals(this.attestationData, registercompletePayload.attestationData) &&
        Objects.equals(this.clientData, registercompletePayload.clientData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(challenge, credentialId, id, rawId, attestationData, clientData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegistercompletePayload {\n");

    sb.append("    challenge: ").append(toIndentedString(challenge)).append("\n");
    sb.append("    credentialId: ").append(toIndentedString(credentialId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    rawId: ").append(toIndentedString(rawId)).append("\n");
    sb.append("    attestationData: ").append(toIndentedString(attestationData)).append("\n");
    sb.append("    clientData: ").append(toIndentedString(clientData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
