/*
 * LoginID Service API
 * # Introduction  <span class=\"subtext\"> Welcome to the LoginID API docs. This documentation will help understand the API calls being made behind our SDKs.  These APIs can be used to manage authentication, users, and user credentials. </span>  # Authentication  <span class=\"subtext\"> There is one main form of authentication for the API: <br/>&bull; API Service Token </span> 
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.loginid.sdk.java.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * InlineResponse200
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-10T08:30:05.952Z[GMT]")
public class RegisterFido2InitResponse {
  @SerializedName("attestation_payload")
  private InlineResponse200AttestationPayload attestationPayload = null;

  @SerializedName("register_session")
  private String registerSession = null;

  public RegisterFido2InitResponse attestationPayload(InlineResponse200AttestationPayload attestationPayload) {
    this.attestationPayload = attestationPayload;
    return this;
  }

   /**
   * Get attestationPayload
   * @return attestationPayload
  **/
  @Schema(description = "")
  public InlineResponse200AttestationPayload getAttestationPayload() {
    return attestationPayload;
  }

  public void setAttestationPayload(InlineResponse200AttestationPayload attestationPayload) {
    this.attestationPayload = attestationPayload;
  }

  public RegisterFido2InitResponse registerSession(String registerSession) {
    this.registerSession = registerSession;
    return this;
  }

   /**
   * Get registerSession
   * @return registerSession
  **/
  @Schema(example = "b34877e9-54ac-4c43-8ea8-5b9bd8732980", description = "")
  public String getRegisterSession() {
    return registerSession;
  }

  public void setRegisterSession(String registerSession) {
    this.registerSession = registerSession;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegisterFido2InitResponse registerFido2InitResponse = (RegisterFido2InitResponse) o;
    return Objects.equals(this.attestationPayload, registerFido2InitResponse.attestationPayload) &&
        Objects.equals(this.registerSession, registerFido2InitResponse.registerSession);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attestationPayload, registerSession);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200 {\n");

    sb.append("    attestationPayload: ").append(toIndentedString(attestationPayload)).append("\n");
    sb.append("    registerSession: ").append(toIndentedString(registerSession)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
